version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: qbuser
      POSTGRES_PASSWORD: qbpass
      POSTGRES_DB: qbhealth
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    image: your-dockerhub-username/qb-backend:latest
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: qbuser
      DATABASE_PASSWORD: qbpass
      DATABASE_NAME: qbhealth
    depends_on:
      - db
    ports:
      - "5000:5000"

  frontend:
    image: your-dockerhub-username/qb-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  db_data:
